; Complete listing of all PKZIP/PKUNZIP config options.
; Note that equal signs and commas are ignored, as well as text after
; semicolon. Multiple options on one line are legal.  All options are
; case insensitive.  Values from the first column are used by default
; by PKZIP/PKUNZIP

;  DEFAULT             COMMAND LINE OPTIONS         CONFIGURATION OPTIONS
;  -------             --------------------         ---------------------
[pkzip]           ;PKZIP configuration options
ANSI=Disabled     ;-q-,-q                        <Disabled | Enabled>
ZIPDATE=Current   ;-k-, -k, -o                   <Current | Keep | Latest>
INCLUDE=None      ;-w<h,s>                       <System, Hidden>
MASK=None         ;-j<s,h,r,a>                   <System,Hidden,ReadOnly,
                  ;                                Archive>
PATHS=None        ;-P, -p(used only with -r)     <All | Recurse | None>
RECURSE=Off       ;-r                            <On | OFF>
COMPRESS=Normal   ;-e[xx,x,n,f,s,0]              <Extreme | Maximum | Normal
                  ;                               | Fast | Speed | Store>
VIEW=None         ;-v[n,e,s,d,n,p] +             <Extension | Size | Date
                  ;                               | Name | Percentage,
                  ;-v<c,r,m>                      Comments, Reverse, More,
                  ;-v<b,t>                        Brief | Long>
LISTCHAR=@        ;List character
OPTIONCHAR=-      ;Option charecter
EMS=Enabled       ;-+ (disable EMS)              <Enabled | Disabled>
XMS=Enabled       ;-- (disable XMS/UMB)          <Enabled | Disabled>
NET=Enabled       ;-~ (disable Network)          <Enabled | Disabled>
386=Enabled       ;-3 (disable 32-bit instruc.)  <Enabled | Disabled>
DPMI=Enabled             ;-) (disable DPMI)      <Enabled | Disabled>
EXPMEMSPOOL=Enabled      ;-%+, -%                <Enabled | Disabled>
USELFN=Enabled           ;-n+, -n                <Enabled | Disabled>
SLOWMEMCOPY=Off   ;-(                            <OFF | ON>
BACKUP=None       ;-&[f,u,w]<l,h><v,s>           <Span,Format | Unconditional
                  ;                               | Wipe, Low | High, Verify,
                  ;                               Full>

[PKUNZIP]         ;PKUNZIP configuration options
DIRECTORIES=Disabled  ;-d-, -d                   <Disabled | Enabled>
ANSI=Disabled     ;-q-, -q                       <Disabled | Enabled>
EMS=Enabled       ;-+ (disable EMS)              <Enabled | Disabled>
XMS=Enabled       ;-- (disable XMS/UMB)          <Enabled | Disabled>
386=Enabled       ;-3 (disable 32-bit instruc.)  <Enabled | Disabled>
DPMI=Enabled      ;-) (disable DPMI)             <Enabled | Disabled>
LISTCHAR=@        ;List character
OPTIONCHAR=-      ;Option character
NEWER=Disabled    ;-n                            <Disabled | Enabled>
FRESHEN=Disabled  ;-f                            <Disabled | Enabled>
LABEL=Disabled    ;-$                            <Disabled | Enabled>
VIEW=None         ;-v[c,e,s,d,n,p][r][m]         <CRC | Extentsion
                  ;                               | Size | Date | Name | Per-
                  ;                               sentage, Reverse, More,
                  ;-v<b,t>                        Brief, Long>
OVERWRITE=Never   ;-o-, -o                       <Never, Always>
MASK=System,Hidden,ReadOnly,Archive
                  ;-j<s,h,r,a>                   <System, Hidden, ReadOnly,
                  ;                               Archive>
PASS=None         ;-J<s,h,r,a>                   <System, Hidden, ReadOnly,
                  ;                               Archive>
SORT=None         ;-e[c,e,s,d,n,p][r]            <Natural |  CRC | Extension
                  ;                               | Size | Date | Name | Per-
                  ;                               centage, Reverse>
PRINT=None        ;p[a/b][c][#]                  <ASC | BIN, COM, [n]>
